version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/app
